In [1]:
from classes.parameter import Parameter, NormalP, TruncNormalP, LognormalP, UniformP

In [2]:
from classes.case import Case

In [3]:
from classes.objfunction import ObjFunction, Np, Wp

In [4]:
from classes.study import Study

In [5]:
from classes.model import Model, Simulator

In [6]:
#from classes.scheduler import Scheduler

In [7]:
#from classes.analysis import Analysis

In [8]:
#from classes.iua import IUA

In [9]:
import pandas as pd
import numpy as np

In [10]:
dftest = pd.read_csv('test\\test_case.csv',sep=';')

# Test Case
### method: read_temp

In [11]:
df = dftest[dftest['class'] == 'Case']
df = df[df['method'] == 'readTemp']
df.head()

class    method                       descrição resultado esperado  \
0  Case  readTemp    caminho válido para template   Nenhuma mensagem   
1  Case  readTemp  caminho inválido para template   Mensagem de erro   

                      Resultado Status     p1  \
0                           NaN     ok  caso0   
1  Error 4: File/Path not found     ok  caso0   

                                                  p2  p3  p4  p5  p6  p7  p8  
0  E:\Dropbox\CodeBunker\MESTRADO\S3_PFP\UAA\proj... NaN NaN NaN NaN NaN NaN  
1                                            asdfadf NaN NaN NaN NaN NaN NaN

In [12]:
for i, row in df.iterrows():
    print('\n=========',row['descrição'])
    case = Case(row['p1'], row['p2']) #, row['p3'])
    case.readTemp()


========= caminho válido para template

========= caminho inválido para template
Error 4: File/Path not found.


# Test OF
### method: calc

In [13]:
df = dftest[dftest['class'] == 'Np']
df = df[df['method'] == 'calc']
df.head()

class method                                 descrição resultado esperado  \
2    Np   calc      Cálculo do Np para data inicial zero              30000   
3    Np   calc  Cálculo do Np para data inicial não nula             475460   
4    Np   calc              Data inicial maior que final   Mensagem de erro   
5    Np   calc                         Data não simulada   Mensagem de erro   

                Resultado Status   p1    p2         p3  p4  p5  p6  p7  p8  
2                   30000     ok  of1     0      120.0 NaN NaN NaN NaN NaN  
3                  475460     ok  of2   120     3270.0 NaN NaN NaN NaN NaN  
4  Error 5: Invalid date.     ok  of3  3720      120.0 NaN NaN NaN NaN NaN  
5  Error 5: Invalid date.     ok  of4     0  1000000.0 NaN NaN NaN NaN NaN

In [14]:
fwell = r'E:\Dropbox\CodeBunker\MESTRADO\S3_PFP\UAA\test\test.well'
#fwell = r'E:\Dropbox\Mestrado\S3\S3_PFP\Diagramas\teste\UA_Injection2\RUN\comp71_00001\UA_Injection_comp71_00001.well'
dfwell = pd.read_csv(fwell, skiprows=[0,1,2],sep = '\t')
dfwell = dfwell.set_index('Time')
dfwell.head()

Date  P1 [OPR]  P1 [WPR]  P1 [LPR]  P1 [BHP]   P1 [OPT]  \
Time                                                                   
120.0   2008-4-30   100.000     0.000    1000.0    1000.0  12000.000   
270.0   2008-9-27    95.123     4.877    1000.0    1000.0  26268.441   
420.0   2009-2-24    90.484     9.516    1000.0    1000.0  39841.003   
570.0   2009-7-24    86.071    13.929    1000.0    1000.0  52751.622   
720.0  2009-12-21    81.873    18.127    1000.0    1000.0  65032.584   

       P1 [WPT]  P2 [OPR]  P2 [WPR]  P2 [LPR]  P2 [BHP]   P2 [OPT]   P2 [WPT]  \
Time                                                                            
120.0     0.000   150.000     0.000    1000.0    1000.0  18000.000      0.000   
270.0   731.559   142.684     7.316    1000.0    1000.0  39402.662   1097.338   
420.0  2158.997   135.726    14.274    1000.0    1000.0  59761.504   3238.496   
570.0  4248.378   129.106    20.894    1000.0    1000.0  79127.433   6372.567   
720.0  6967.416   122.810    27.190    1000.0    1000.0  97548.875  10451.125   

          totalNp    totalWp  Unnamed: 16  
Time                                       
120.0   30000.000      0.000          NaN  
270.0   65671.103   1828.897          NaN  
420.0   99602.507   5397.493          NaN  
570.0  131879.056  10620.944          NaN  
720.0  162581.459  17418.541          NaN

In [15]:
for i, row in df.iterrows():
    print('\n=========',row['class'], row['method'],row['descrição'])
    # ofName, ini, end, delta = False)
    of = Np(row['p1'], float(row['p2']), float(row['p3'])) #, row['p3'])
    try:
        ofv = of.calc(dfwell)
        ofv = np.round(ofv)
        ofexp = dfwell['totalNp'][float(row['p3'])]
        ofexp = np.round(ofexp)
        if float(row['p2'])!=0:
            ofexp = ofexp-dfwell['totalNp'][float(row['p2'])]
            ofexp = np.round(ofexp)
        print(ofv,ofexp, ofv == ofexp)
    except:
        pass





========= Np calc Cálculo do Np para data inicial zero
30000.0 30000.0 True

========= Np calc Cálculo do Np para data inicial não nula
475460.0 475460.0 True

========= Np calc Data inicial maior que final
Error 5: Invalid date.

========= Np calc Data não simulada
Error 5: Invalid date.


In [16]:
df = dftest[dftest['class'] == 'Wp']
df = df[df['method'] == 'calc']
df.head()

class method                                 descrição resultado esperado  \
6    Wp   calc      Cálculo do Wp para data inicial zero                  0   
7    Wp   calc  Cálculo do Wp para data inicial não nula             312040   
8    Wp   calc              Data inicial maior que final   Mensagem de erro   
9    Wp   calc                         Data não simulada   Mensagem de erro   

                Resultado Status   p1    p2         p3  p4  p5  p6  p7  p8  
6                       0     ok  of1     0      120.0 NaN NaN NaN NaN NaN  
7                  312040     ok  of2   120     3270.0 NaN NaN NaN NaN NaN  
8  Error 5: Invalid date.     ok  of3  3720      120.0 NaN NaN NaN NaN NaN  
9  Error 5: Invalid date.     ok  of4     0  1000000.0 NaN NaN NaN NaN NaN

In [17]:
for i, row in df.iterrows():
    print('\n=========',row['class'], row['method'],row['descrição'])
    # ofName, ini, end, delta = False)
    of = Wp(row['p1'], float(row['p2']), float(row['p3'])) #, row['p3'])
    try:
        ofv = of.calc(dfwell)
        ofv = np.round(ofv)
        ofexp = dfwell['totalWp'][float(row['p3'])]
        ofexp = np.round(ofexp)
        if float(row['p2'])!=0:
            ofexp = ofexp-dfwell['totalWp'][float(row['p2'])]
            ofexp = np.round(ofexp)
        print(ofv,ofexp, ofv == ofexp)
    except:
        pass


========= Wp calc Cálculo do Wp para data inicial zero
0.0 0.0 True

========= Wp calc Cálculo do Wp para data inicial não nula
312040.0 312040.0 True

========= Wp calc Data inicial maior que final
Error 5: Invalid date.

========= Wp calc Data não simulada
Error 5: Invalid date.


# Test Study
### method: designExp

In [18]:
df = dftest[dftest['class'] == 'Study']
df = df[df['method'] == 'designExp']
df.head()

class     method                                  descrição  \
10  Study  designExp   Número de parâmetros 1 e amostras válido   
11  Study  designExp  Número de parâmetros válido  e amostras 1   
12  Study  designExp     Número de parâmetros e amostras válido   
13  Study  designExp                  Número de parâmetros zero   
14  Study  designExp                    Número de amostras zero   

   resultado esperado                Resultado Status    p1 p2   p3  p4  p5  \
10          Gerar DOE  DOE gerado corretamente     ok  std1  5  1.0 NaN NaN   
11          Gerar DOE  DOE gerado corretamente     ok  std2  1  5.0 NaN NaN   
12          Gerar DOE  DOE gerado corretamente     ok  std3  5  5.0 NaN NaN   
13        lista vazia              lista vazia     ok  std4  5  0.0 NaN NaN   
14               erro                     erro     ok  std5  0  5.0 NaN NaN   

    p6  p7  p8  
10 NaN NaN NaN  
11 NaN NaN NaN  
12 NaN NaN NaN  
13 NaN NaN NaN  
14 NaN NaN NaN

In [19]:
for i, row in df.iterrows():
    print('\n=========',row['class'], row['method'],row['descrição'])
    # stName,path, nsamples
    std = Study(row['p1'],'', int(row['p2']))
    std.npar = int(row['p3'])
    std.parameters =[]
    for i in range(std.npar):
        std.parameters.append(TruncNormalP('Prop1',0.3,0.1,0.1,1))
    try:
        std.designExp()
        print(std.experiments)
    except:
        print('erro DOE')


========= Study designExp Número de parâmetros 1 e amostras válido
[[0.32147639]
 [0.19129819]
 [0.33742208]
 [0.26832744]
 [0.39753013]]

========= Study designExp Número de parâmetros válido  e amostras 1
[[0.24563107 0.43897846 0.22818043 0.227591   0.29105419]]

========= Study designExp Número de parâmetros e amostras válido
[[0.17791711 0.34446567 0.20546245 0.23894565 0.37617448]
 [0.27562172 0.2589287  0.38105342 0.35953001 0.257677  ]
 [0.41241325 0.38661862 0.42027703 0.41037352 0.21674761]
 [0.28162897 0.28609144 0.22527237 0.30434375 0.38905772]
 [0.34746938 0.16617808 0.29220779 0.17631927 0.29632897]]

========= Study designExp Número de parâmetros zero
[]

========= Study designExp Número de amostras zero
erro DOE

========= Study designExp Número de parâmetros negativo
erro DOE

========= Study designExp Número de amostras negativo
erro DOE
